# prometheus.yml
global:
    scrape_interval: 3s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter:9100']
    - job_name: 'traefik'
      static_configs:
      - targets: ['reverse-proxy:8082']
    - job_name: 'rabbitmq-exporter'
      static_configs:
      - targets: ['rabbitmq-exporter:9419']
